### PR TITLE
Update molex-ont.md

### PR DESCRIPTION
**Pull request by sillawned**
Added a link to the final design with all the components on EasyEDA.

### CODE REVIEW

**Comment by simonebortolin** [comment]
I do not see the usefulness of this pr

**Comment by nanomad** [comment]
@sillawned The linked project seems empty. Feel free to re-open the PR once you publish everything on oshwlab

**Comment by sillawned** [comment]
Yeah, I'm waiting the shipping of the components to upload a real photo and change the project to final on their website.

@simonebortolin I put the link as a PR because I lost few hours researching how to create and buy a custom PCB. The goal is to provide a project with all the files ready to export (from an online EDA) and drag'n'drop it on any seller website of custom PCB.

**Comment by sillawned** [comment]
The project is under review by the oshwlab team. I added one photo and the BOM to it.

**Comment by sillawned** [comment]
@nanomad The oshwlab project is complete and accepted. Feel free to review it, maybe I'm missing some credits in the description.

**Review by simonebortolin — APPROVED** [review]

**Pull request merged**
