### PR TITLE
Update ont-leox-lxt-010h-d.md

### PR DESCRIPTION
**Pull request by tompointexe**
Adding aditional login informations for the Leox lxt-010h-d

### CODE REVIEW

**Comment by simonebortolin** [comment]
please format the table

**Comment by tompointexe** [comment]
Hi, How ? 😅

**Comment by simonebortolin** [comment]
no need to close the PR, you can add new commits to this PR then we do the squash.

any markdown ide has support for table formatting, otherwise you can do it manually.

your pr is acceptable as long as you fix the table

**Comment by tompointexe** [comment]
Yes my bad, i just renamed the branch, that's why it closed itself, sorry, i'l try to reformat it 👍

**Comment by tompointexe** [comment]
Table should be formated correctly now, sorry, i'm new to markdown and pull request

**Review by simonebortolin — APPROVED** [review]

**Pull request merged**
